language: node_js
node_js:
  - "12"
install:
    - npm install
script:
    - npm test
deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_AUTH_TOKEN
    app: line-bot-halley
    on:
      branch: main
      